### ISSUE TITLE
OAI dataset Request

### ISSUE THREAD

**Issue by ghost** [antonyalexos/Accelerometer-Knee-Osteoarthritis-Prediction#1]
I have requested to access data in the Osteoarthritis Initiative but it takes 2 months from now the website is still not working
can you please share the dataset?

**Comment by antonyalexos** [comment]
I cannot share the whole dataset. It's a very big file actually. It does take time for the request to go through. As you can see on the repo I have the specific data that you need in order to run the code.

**Comment by ghost** [comment]
I know it takes time but I need Dicom files, if you can share I will be very thankful to you.

**Comment by antonyalexos** [comment]
I am not allowed to share the data unfortunately. If you try to contact the OAI though they will assist you.

**Comment by ghost** [comment]
Do you have a DICOM files dataset?

**Comment by antonyalexos** [comment]
I think I have them in an old hard drive but I can't say for sure

**Comment by ghost** [comment]
Ok, bro thanks
